"""users table

Revision ID: 3c36259ff152
Revises: 80de6e93af88
Create Date: 2018-02-22 12:03:02.445423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c36259ff152'
down_revision = '80de6e93af88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_blocked', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('permissions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permissions')
    op.drop_column('users', 'is_blocked')
    # ### end Alembic commands ###
